on:
  push:
    branches: [main]
name: TOC Generator
jobs:
  generateTOC:
    name: TOC Generator
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@9e238e7974de5fcf7b17b7acc54c896160dda0a3 # v4
        with:
          TOC_TITLE: ""
